

# kitti data set

path: /content/drive/My Drive/Kitti dataset/images/
train: train
val: train
test: train

nc: 9
names: ["Car","Pedestrian","Van","Cyclist","Truck","Misc","Tram","Person_sitting","DontCare"]
